#!/usr/bin/env bash
# Generate niri border + overview + recent-window colors from the wallust palette.
#
# Writes a GENERATED, gitignored includes/colors.kdl that overrides the static
# fallback colors in layout.kdl. niri deep-merges later includes per leaf, so
# only the color keys change — layout structure stays in the tracked layout.kdl.
# This keeps layout.kdl from being rewritten on every wallpaper change.

COLORS="$HOME/.cache/wal/colors.json"

# Canonical includes dir — follows the ~/.config/niri -> repo symlink so the
# generated file lands next to layout.kdl wherever the repo is cloned.
INCLUDES_DIR="$(readlink -f "$HOME/.config/niri/includes" 2>/dev/null)"
OUT="$INCLUDES_DIR/colors.kdl"

# Wallust slot for overview backdrop (color8 = bright-black, elevated surface).
# Override via env: OVERVIEW_COLOR_KEY=color1 (warm accent) etc.
OVERVIEW_COLOR_KEY="${OVERVIEW_COLOR_KEY:-color8}"

[ -f "$COLORS" ] || { echo "wal colors.json not found" >&2; exit 1; }
[ -d "$INCLUDES_DIR" ] || { echo "niri includes dir not found ($INCLUDES_DIR)" >&2; exit 1; }

# Slot choice mirrors quickshell services/theme: color6 = accent (vibrant
# readable), color8 = bgVariant (medium tint). color0 often collapses to near
# pure black, so color8 keeps inactive border + overview bg wallpaper-bound.
active=$(jq -r '.colors.color6' "$COLORS")
inactive=$(jq -r '.colors.color8' "$COLORS")
layout_bg=$(jq -r '.colors.color8' "$COLORS")
overview_backdrop=$(jq -r ".colors.${OVERVIEW_COLOR_KEY}" "$COLORS")
# color1 = warm/error slot (mirrors Colors.error in quickshell)
urgent_base=$(jq -r '.colors.color1' "$COLORS")

# Abort if any value missing/null — prevents writing empty strings to config
for v in active inactive layout_bg overview_backdrop urgent_base; do
    val="${!v}"
    if [ -z "$val" ] || [ "$val" = "null" ]; then
        echo "color '$v' empty or null — aborting" >&2
        exit 1
    fi
done

# Recent-windows highlight = accent + 60% alpha (overlay on focused thumbnail)
recent_highlight="${active}99"
# Urgent = error/warm slot + 80% alpha (stronger than active for attention)
recent_urgent="${urgent_base}cc"

cat > "$OUT" <<EOF
// GENERATED by scripts/pywal-niri-colors.sh from the wallust palette.
// DO NOT EDIT, DO NOT COMMIT — gitignored. Overrides the static fallback
// colors in layout.kdl (niri deep-merges later includes per leaf).
layout {
    background-color "$layout_bg"
    border {
        active-color "$active"
        inactive-color "$inactive"
    }
}

overview {
    backdrop-color "$overview_backdrop"
}

recent-windows {
    highlight {
        active-color "$recent_highlight"
        urgent-color "$recent_urgent"
    }
}
EOF

# Reload niri config if running
niri msg action load-config-file 2>/dev/null || true
