foreground         #d8dee9
background         {{background}}
cursor             #f2f4f8
cursor_text_color  {{background}}
selection_foreground #f2f4f8
selection_background {{color8}}
url_color          {{color6}}
active_tab_foreground     {{background}}
active_tab_background     #d8dee9
inactive_tab_foreground   #b8c0cc
inactive_tab_background   {{background}}
color0 {{color0}}
color1 {{color1}}
color2 {{color2}}
color3 {{color3}}
color4 {{color4}}
color5 {{color5}}
color6 {{color6}}
color7 #b8c0cc
color8 {{color8}}
color9 {{color9 | lighten(0.15) | saturate(0.15)}}
color10 {{color10 | lighten(0.15) | saturate(0.15)}}
color11 {{color11 | lighten(0.15) | saturate(0.15)}}
color12 {{color12 | lighten(0.15) | saturate(0.15)}}
color13 {{color13 | lighten(0.15) | saturate(0.15)}}
color14 {{color14 | lighten(0.15) | saturate(0.15)}}
color15 #f2f4f8
