[mgr]
cwd = { fg = "#0466E6" }

hovered         = { fg = "#010019", bg = "#0466E6" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#0C41C4", italic = true }
find_position = { fg = "#BC04FD", bg = "reset", italic = true }

marker_selected = { fg = "#071193", bg = "#071193" }
marker_copied   = { fg = "#0C41C4", bg = "#0C41C4" }
marker_cut      = { fg = "#010E49", bg = "#010E49" }

tab_active   = { fg = "#010019", bg = "#0466E6" }
tab_inactive = { fg = "#1A1C2D", bg = "#010019" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#1A1C2D" }

syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#010019", bg = "#010019" }

mode_normal = { fg = "#010019", bg = "#2FC3E7", bold = true }
mode_select = { fg = "#010019", bg = "#071193", bold = true }
mode_unset  = { fg = "#010019", bg = "#BC04FD", bold = true }

progress_label  = { fg = "#CBECEF", bold = true }
progress_normal = { fg = "#0466E6",    bg = "#010019" }
progress_error  = { fg = "#010E49", bg = "#010019" }

permissions_t = { fg = "#071193" }
permissions_r = { fg = "#0C41C4" }
permissions_w = { fg = "#010E49" }
permissions_x = { fg = "#0466E6" }
permissions_s = { fg = "#1A1C2D" }

[input]
border   = { fg = "#0466E6" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#0466E6" }
active   = { fg = "#0C41C4" }
inactive = {}

[tasks]
border  = { fg = "#0466E6" }
title   = {}
hovered = { underline = true }

[which]
cols            = 3
mask            = { bg = "#010019" }
cand            = { fg = "#071193" }
rest            = { fg = "#1A1C2D" }
desc            = { fg = "#0C41C4" }
separator       = "  "
separator_style = { fg = "#010019" }

[help]
on      = { fg = "#0C41C4" }
exec    = { fg = "#071193" }
desc    = { fg = "#1A1C2D" }
hovered = { bg = "#010019", bold = true }
footer  = { fg = "#010019", bg = "#CBECEF" }

[filetype]
rules = [
    { mime = "image/*",                    fg = "#071193" },
    { mime = "video/*",                    fg = "#0C41C4" },
    { mime = "audio/*",                    fg = "#0C41C4" },
    { mime = "application/zip",            fg = "#BC04FD" },
    { mime = "application/gzip",           fg = "#BC04FD" },
    { mime = "application/x-tar",          fg = "#BC04FD" },
    { mime = "application/x-bzip",         fg = "#BC04FD" },
    { mime = "application/x-bzip2",        fg = "#BC04FD" },
    { mime = "application/x-7z-compressed",fg = "#BC04FD" },
    { mime = "application/x-rar",          fg = "#BC04FD" },
    { name = "*",  fg = "#CBECEF" },
    { name = "*/", fg = "#0466E6" },
]
