# : Manager [[[

[manager]
cwd = { fg = "#e4e1e9" }

# Tab
tab_active = { fg = "#2a2a60", bg = "#c2c1ff", bold = true }
tab_inactive = { fg = "#e2dfff", bg = "#14134a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff72b7", bg = "#ff72b7" }
marker_cut = { fg = "#ffd8eb", bg = "#ffd8eb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e9b9d2", bg = "#e9b9d2" }

# Count
count_copied = { fg = "#2f1124", bg = "#ffd8eb" }
count_cut = { fg = "#2f1124", bg = "#ffd8eb" }
count_selected = { fg = "#2a2a60", bg = "#e9b9d2" }

# Border
border_symbol = "│"
border_style  = { fg = "#c2c1ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#2a2a60", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c2c1ff", fg = "#2a2a60", bold = true }
normal_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Select mode
select_main = { bg = "#c6c4dd", fg = "#2f2f42", bold = true }
select_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Unset mode
unset_main = { bg = "#e9b9d2", fg = "#47263a", bold = true }
unset_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c2c1ff", bg = "#39383f" }
progress_error = { fg = "#ffb4ab", bg = "#39383f" }

# Permissions
permissions_t = { fg = "#6863a5" }
permissions_w = { fg = "#c44587" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3f9d" }
permissions_s = { fg = "#5746ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c2c1ff" }
active = { fg = "#e9b9d2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c2c1ff" }
value = { fg = "#e4e1e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c2c1ff", bg = "#2a2a60" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c2c1ff" }
title = {}
hovered = { fg = "#ffd8eb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39383f" }
cand = { fg = "#c2c1ff" }
rest = { fg = "#2a2a60" }
desc = { fg = "#e4e1e9" }
separator = " ▶ "
separator_style = { fg = "#e4e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e1e9" }
run = { fg = "#e4e1e9" }
footer = { fg = "#2f2f42", bg = "#c6c4dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e9b9d2" }
title_warn = { fg = "#c2c1ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e4e1e9" },
    { name = "*/", fg = "#c2c1ff" },
]

# : ]]]