################
### MONITORS ###
################

monitor = eDP-1, disable
monitor = desc:Microstep Optix MAG24C REDACTED-SERIAL, preferred, -1920x360, auto
monitor = desc:Microstep G274QPF-QD REDACTED-SERIAL, 2560x1440@144, 0x0, auto