################
### MONITORS ###
################
monitor = eDP-1, disable
monitor = desc:Microstep Optix MAG24C REDACTED-SERIAL, 1920x1080@120, -1920x0, auto, cm, auto
monitor = desc:Microstep G274QPF-QD REDACTED-SERIAL, 2560x1440@144, 0x0, auto, cm, auto
